name: Elysium Plugin for Logseq Release 
on:
  push:
    tags:
      - 'v*.*.*'

env:
  PLUGIN_NAME: logseq-elysium

jobs:
  build:
    name: Build Elysium Plugin and Release Elysium Plugin for Logseq
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp -R LICENSE package.json README.md style.css media/ ${{ env.PLUGIN_NAME }} 
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }} 

      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with: 
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          draft: false
          files: |
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.PLUGIN_NAME }}/
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
